version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: pbl-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - pbl-network

volumes:
  redis_data:
    driver: local

networks:
  pbl-network:
    driver: bridge